const en = {
  saved: 'Saved papers',
  recent: 'Recently read',
  cached: 'On this device',
  folders: 'Paper folders',
  tags: 'Tags',
  allTags: 'All tags',
  title: 'THE RESEARCH INDEX',
  deck: 'Keep sources close. Follow the ideas that branch from them.',
  import: 'Add a paper',
  papers: 'papers',
  save: 'Save paper',
  unsave: 'Remove from saved',
  retained: 'PDF, reading history and notes stay on this device.',
  read: 'Read →',
  resume: 'Continue reading →',
  sort: 'Sort papers',
  newest: 'Latest activity',
  alphabetical: 'Title A–Z',
  oldest: 'First added',
  filter: 'Reading status',
  anyStatus: 'Any reading status',
  unread: 'Unread',
  reading: 'Reading',
  readStatus: 'Read',
  unknownProgress: 'No reading position yet',
  authorsUnknown: 'Authors not available',
  publicationUnknown: 'Publication not available',
  metadataOnly: 'Bibliography only',
  progress: 'Reading position',
  search: 'Search titles, authors, DOI, folders or tags',
  clear: 'Clear filters',
  loading: 'Loading the research index…',
  retry: 'Try again',
  emptySaved: 'Your saved research starts here.',
  emptyRecent: 'No papers have been read yet.',
  emptyCached: 'No PDFs on this device yet.',
  emptyFolder: 'This folder has no papers yet.',
  noMatch: 'No papers match these filters.',
  emptyDeck: 'Add a PDF or open a paper address. Saving is a separate choice.',
  showCached: 'Browse papers on this device',
  showSaved: 'Browse saved papers',
  organize: 'Folders & tags',
  edit: 'Edit folders & tags',
  newFolder: 'New folder',
  childFolder: 'New child folder',
  editFolder: 'Rename or move folder',
  deleteFolder: 'Remove folder',
  folderName: 'Folder name',
  parent: 'Parent folder',
  root: 'Top level',
  folderActions: 'Folder actions',
  expand: 'Expand folder',
  collapse: 'Collapse folder',
  deleteFolderBody: 'Papers and notes are retained. Immediate child folders move to this folder’s parent; only this folder membership is removed.',
  done: 'Apply changes',
  tagHint: 'Separate tags with commas.',
  memberships: 'Choose any number of folders.',
  deletePaper: 'Delete local paper…',
  page: 'Page',
  unavailable: 'The research index could not be loaded.',
  mutationError: 'Changes could not be saved. Your choices are still here; try again.',
  folderEmpty: 'Create folders to organize a paper in more than one place.',
  openSource: 'Open source',
  shown: 'shown',
};
const ko: typeof en = {
  saved: '저장한 논문',
  recent: '최근 읽은 논문',
  cached: '이 기기의 논문',
  folders: '논문 폴더',
  tags: '태그',
  allTags: '모든 태그',
  title: 'THE RESEARCH INDEX',
  deck: '원문 가까이에서, 가지처럼 이어지는 생각을 따라가세요.',
  import: '논문 추가',
  papers: '편의 논문',
  save: '논문 저장',
  unsave: '저장 목록에서 제거',
  retained: 'PDF, 읽기 기록과 메모는 이 기기에 남습니다.',
  read: '읽기 →',
  resume: '이어 읽기 →',
  sort: '논문 정렬',
  newest: '최근 활동순',
  alphabetical: '제목순',
  oldest: '추가한 순서',
  filter: '읽기 상태',
  anyStatus: '모든 읽기 상태',
  unread: '읽지 않음',
  reading: '읽는 중',
  readStatus: '읽음',
  unknownProgress: '아직 읽기 위치가 없습니다',
  authorsUnknown: '저자 정보 없음',
  publicationUnknown: '출판 정보 없음',
  metadataOnly: '서지 정보만 있음',
  progress: '읽기 위치',
  search: '제목, 저자, DOI, 폴더 또는 태그 검색',
  clear: '필터 초기화',
  loading: '연구 목록을 불러오는 중…',
  retry: '다시 시도',
  emptySaved: '저장할 연구를 모아보세요.',
  emptyRecent: '아직 읽은 논문이 없습니다.',
  emptyCached: '이 기기에 PDF가 없습니다.',
  emptyFolder: '아직 이 폴더에 논문이 없습니다.',
  noMatch: '필터에 맞는 논문이 없습니다.',
  emptyDeck: 'PDF나 논문 주소를 열어보세요. 저장은 별도로 선택합니다.',
  showCached: '이 기기의 논문 보기',
  showSaved: '저장한 논문 보기',
  organize: '폴더 및 태그',
  edit: '폴더 및 태그 편집',
  newFolder: '새 폴더',
  childFolder: '하위 폴더 만들기',
  editFolder: '폴더 이름 및 위치 변경',
  deleteFolder: '폴더 제거',
  folderName: '폴더 이름',
  parent: '상위 폴더',
  root: '최상위',
  folderActions: '폴더 작업',
  expand: '폴더 펼치기',
  collapse: '폴더 접기',
  deleteFolderBody: '논문과 메모는 유지됩니다. 바로 아래의 폴더는 상위 폴더로 이동하고, 이 폴더의 논문 소속만 제거됩니다.',
  done: '변경 적용',
  tagHint: '태그를 쉼표로 구분하세요.',
  memberships: '여러 폴더를 선택할 수 있습니다.',
  deletePaper: '로컬 논문 삭제…',
  page: '페이지',
  unavailable: '연구 목록을 불러오지 못했습니다.',
  mutationError: '변경을 저장하지 못했습니다. 선택한 내용은 유지되며 다시 시도할 수 있습니다.',
  folderEmpty: '폴더를 만들어 논문을 여러 곳에 정리하세요.',
  openSource: '출처 열기',
  shown: '편 표시',
};
export const indexCopy = (language: 'ko' | 'en') => (language === 'ko' ? ko : en);
