// Generates platform files from packages/shared/tokens/tokens.json:
//   packages/ui/src/design/tokens.css                 (CSS custom properties, per theme)
//   packages/shared/tokens/generated/FractalTokens.kt  (Android Compose constants)
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'packages/shared/tokens/tokens.json'), 'utf8'));

const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const header = 'Generated by scripts/gen-tokens.mjs from packages/shared/tokens/tokens.json. Do not edit.';

function colorBlock(theme) {
  return Object.entries(tokens.color[theme])
    .map(([name, value]) => `  --c-${kebab(name)}: ${value};`)
    .join('\n');
}

function scalarBlock() {
  const lines = [];
  for (const [name, value] of Object.entries(tokens.font)) lines.push(`  --font-${name}: ${value};`);
  for (const [name, value] of Object.entries(tokens.size)) lines.push(`  --fs-${name}: ${value / 16}rem;`);
  for (const [name, value] of Object.entries(tokens.space)) lines.push(`  --sp-${name}: ${value}px;`);
  for (const [name, value] of Object.entries(tokens.radius)) lines.push(`  --r-${name}: ${value}px;`);
  for (const [name, value] of Object.entries(tokens.motion)) {
    lines.push(`  --motion-${name}: ${typeof value === 'number' ? `${value}ms` : value};`);
  }
  return lines.join('\n');
}

const css = `/* ${header} */
:root {
${scalarBlock()}
${colorBlock('light')}
  color-scheme: light;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme]) {
${colorBlock('dark').replace(/^/gm, '  ')}
    color-scheme: dark;
  }
}

:root[data-theme='dark'] {
${colorBlock('dark')}
  color-scheme: dark;
}

:root[data-theme='sepia'] {
${colorBlock('sepia')}
  color-scheme: light;
}
`;

function kotlinColor(value) {
  const hex = /^#([0-9a-f]{6})$/i.exec(value);
  if (hex) return `Color(0xFF${hex[1].toUpperCase()})`;
  const rgba = /^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/.exec(value);
  if (rgba) {
    const [r, g, b] = rgba.slice(1, 4).map(Number);
    const a = Math.round(Number(rgba[4]) * 255);
    const h = (n) => n.toString(16).padStart(2, '0').toUpperCase();
    return `Color(0x${h(a)}${h(r)}${h(g)}${h(b)})`;
  }
  throw new Error(`Unsupported color: ${value}`);
}

const pascal = (s) => s[0].toUpperCase() + s.slice(1);
const colorNames = Object.keys(tokens.color.light);
const kotlin = `// ${header}
package app.fractal.design

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Immutable
data class FractalColors(
${colorNames.map((n) => `    val ${n}: Color,`).join('\n')}
)

object FractalTokens {
${Object.keys(tokens.color)
  .map(
    (theme) => `    val ${theme}Colors = FractalColors(
${colorNames.map((n) => `        ${n} = ${kotlinColor(tokens.color[theme][n])},`).join('\n')}
    )`,
  )
  .join('\n\n')}

${Object.entries(tokens.size)
  .map(([n, v]) => `    val size${pascal(n)} = ${v}.sp`)
  .join('\n')}

${Object.entries(tokens.space)
  .map(([n, v]) => `    val space${n} = ${v}.dp`)
  .join('\n')}

${Object.entries(tokens.radius)
  .map(([n, v]) => `    val radius${pascal(n)} = ${v}.dp`)
  .join('\n')}

    const val motionFastMs = ${tokens.motion.fast}
    const val motionBaseMs = ${tokens.motion.base}
    const val motionSlowMs = ${tokens.motion.slow}
}
`;

const cssPath = resolve(root, 'packages/ui/src/design/tokens.css');
const ktPath = resolve(root, 'packages/shared/tokens/generated/FractalTokens.kt');
mkdirSync(dirname(cssPath), { recursive: true });
mkdirSync(dirname(ktPath), { recursive: true });
writeFileSync(cssPath, css);
writeFileSync(ktPath, kotlin);
console.log(`tokens → ${cssPath}\ntokens → ${ktPath}`);
